# This file contains sample HTTP requests for the DB Open Data Timetables API
#
# Prerequisites
#
# - Register with the DB Open Data developer portal at
#   https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData
#
# - Subscribe to the timetables API
#
# How to run the requests in this file
#
# - Open this file inside a JetBrains IDE (e.g. IntelliJ IDEA) using the HTTP Client plugin
#   (see https://www.jetbrains.com/help/idea/http-client-in-product-code-editor.html)
#
# - "Add environment file" and specify the following JSON:
#   {
#     "sandbox": {
#       "auth_token": "your token from DB Open Data developer portal"
#     }
#   }
#
# - Attention: NEVER CHECK IN THIS FILE!
#
# - When running the requests below, choose the "sandbox" environment
#
# How to interpret the results?
#
# - See "Interface description" document in the tab "Documentation" at
#   https://developer.deutschebahn.com/store/apis/info?name=Timetables&version=v1&provider=DBOpenData

### Query station eva id for Rösrath-Stümpen
GET https://api.deutschebahn.com/timetables/v1/station/r%C3%B6srath-st%C3%BCmpen
Authorization: Bearer {{auth_token}}
Accept: application/xml

### Query all known changes for the station eva id
GET https://api.deutschebahn.com/timetables/v1/fchg/8005143
Authorization: Bearer {{auth_token}}
Accept: application/xml
